name: Deploy Lambda function

on:
  push:
    branches: [main]
    # paths:
    #   - lambda-functions/**

env:
  AWS_REGION: "us-east-1"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./lambda-functions/upload-data-to-mongo-db
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: zip folder
        run: zip -r upload-data-to-mongo-db.zip *

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/poems-and-film-role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload code to S3
        run: |
          aws s3 sync upload-data-to-mongo-db.zip s3://poems-and-film-lambdas/upload-data-to-mongo-db.zip --region us-east-1
